name: Build Server Docker Image

on:
  push:
    branched:
      - devo-1262-self-hosted-codepush

env:
  CONTAINER_REGISTRY: "insight2profitregistry.azurecr.io"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout shared action library
        uses: actions/checkout@v3
        with:
          repository: PRICE-FOR-PROFIT/actions-shared-library
          token: ${{ secrets.GH_PAT_BUILD_ACCOUNT_FORKED }}
          path: actions-remote


      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./api
        run: npm install

      - name: Build Server
        working-directory: ./api
        run: npm run build

      - name: Login to Azure Container Registry
        uses: ./actions-remote/common/docker-login
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME_FORKED }}
          password: ${{ secrets.REGISTRY_PASSWORD_FORKED }}

      - name: Generate Dockertag
        uses: ./actions-remote/common/generate-dockertag
        id: dockertag

      - name: Build Docker Image
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/codepush-${{ steps.dockertag.outputs.branch_name }}:${{ steps.dockertag.outputs.dockertag }} .

      - name: Push Docker Image
        run: docker push ${{ env.CONTAINER_REGISTRY }}/codepush-${{ steps.dockertag.outputs.branch_name }}:${{ steps.dockertag.outputs.dockertag }}
